spring:
  application:
    name: bank
  datasource:
    url: jdbc:mysql://bank-mysql:3306/eazybank
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
  sql:
    init:
      mode: ALWAYS
      schema-locations: classpath:backup/init-schema.sql,classpath:backup/init-data.sql
  output:
    ansi:
      enabled: ALWAYS
  keycloak:
    server-url: https://keycloak.greeta.net
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${spring.keycloak.server-url}/realms/bank-realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs


logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  level:
    org.springframework.cloud.kubernetes: TRACE
    org.springframework.security: DEBUG

info:
  system: Bank Service

jwt:
  auth:
    converter:
      resource-id: bank-app
      principal-attribute: preferred_username

management:
  endpoints:
    web:
      exposure:
        include: bindings, configprops, env, flyway, functions, health, heapdump, info, loggers, mappings, prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}